-- Operational-location foundation (additive, protocol v3).
-- This file creates no branch/location rows and performs no ownership backfill.
-- Apply only after a separately approved mapping and backup.

CREATE TABLE IF NOT EXISTS operational_locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  location_code VARCHAR(80) NOT NULL,
  location_name VARCHAR(180) NOT NULL,
  location_type VARCHAR(60) NOT NULL DEFAULT 'STORE',
  address TEXT,
  timezone VARCHAR(80) NOT NULL DEFAULT 'Asia/Kolkata',
  active BOOLEAN NOT NULL DEFAULT TRUE,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  deactivated_at TIMESTAMP,
  deactivated_by INTEGER REFERENCES users(id),
  deactivation_reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (company_id, branch_id, location_code),
  UNIQUE (company_id, branch_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS operational_locations_one_default_idx
  ON operational_locations(company_id, branch_id)
  WHERE is_default = TRUE AND active = TRUE;

ALTER TABLE product_categories ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE products ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);

CREATE TABLE IF NOT EXISTS operational_location_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  pos_available BOOLEAN NOT NULL DEFAULT TRUE,
  selling_rate NUMERIC(14, 2),
  reorder_level NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
  effective_from TIMESTAMP,
  updated_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (operational_location_id, product_id),
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS staff_location_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  role_id INTEGER REFERENCES roles(id),
  permission_set JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  effective_from DATE,
  effective_to DATE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  assigned_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, operational_location_id),
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id),
  CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE UNIQUE INDEX IF NOT EXISTS staff_location_one_default_idx
  ON staff_location_assignments(user_id, company_id)
  WHERE is_default = TRUE AND active = TRUE;

CREATE TABLE IF NOT EXISTS device_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id VARCHAR(160) NOT NULL REFERENCES authorized_devices(device_id),
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  physical_label VARCHAR(180),
  device_type VARCHAR(80) NOT NULL,
  intended_usage VARCHAR(80) NOT NULL,
  fixed_operational BOOLEAN NOT NULL DEFAULT TRUE,
  permission_set JSONB NOT NULL DEFAULT '{}'::jsonb,
  permitted_user_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
  permitted_roles JSONB NOT NULL DEFAULT '[]'::jsonb,
  assignment_generation INTEGER NOT NULL DEFAULT 1 CHECK (assignment_generation > 0),
  active BOOLEAN NOT NULL DEFAULT TRUE,
  approved_by INTEGER NOT NULL REFERENCES users(id),
  approved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deactivated_at TIMESTAMP,
  deactivated_by INTEGER REFERENCES users(id),
  deactivation_reason TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (device_id, assignment_generation),
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS device_assignments_one_active_idx
  ON device_assignments(device_id)
  WHERE active = TRUE;

CREATE TABLE IF NOT EXISTS device_assignment_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id VARCHAR(160) NOT NULL REFERENCES authorized_devices(device_id),
  assignment_id BIGINT REFERENCES device_assignments(id),
  action VARCHAR(40) NOT NULL,
  old_scope JSONB,
  new_scope JSONB,
  reason TEXT NOT NULL,
  changed_by INTEGER NOT NULL REFERENCES users(id),
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id VARCHAR(180) NOT NULL UNIQUE,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  order_number VARCHAR(80) NOT NULL,
  order_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  created_by INTEGER NOT NULL REFERENCES users(id),
  source_device_id VARCHAR(160) REFERENCES authorized_devices(device_id),
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (company_id, order_number),
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS purchase_order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  ordered_quantity NUMERIC(14, 3) NOT NULL CHECK (ordered_quantity > 0),
  expected_rate NUMERIC(14, 4),
  unit VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS goods_receipts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id VARCHAR(180) NOT NULL UNIQUE,
  purchase_order_id BIGINT REFERENCES purchase_orders(id),
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  grn_number VARCHAR(80) NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(40) NOT NULL DEFAULT 'RECEIVED',
  received_by INTEGER NOT NULL REFERENCES users(id),
  receiving_device_id VARCHAR(160) NOT NULL REFERENCES authorized_devices(device_id),
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (company_id, grn_number),
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS goods_receipt_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  goods_receipt_id BIGINT NOT NULL REFERENCES goods_receipts(id) ON DELETE CASCADE,
  purchase_order_item_id BIGINT REFERENCES purchase_order_items(id),
  product_id INTEGER NOT NULL REFERENCES products(id),
  received_quantity NUMERIC(14, 3) NOT NULL CHECK (received_quantity > 0),
  cost_rate NUMERIC(14, 4),
  lot_global_id VARCHAR(180) NOT NULL
);

CREATE TABLE IF NOT EXISTS supplier_bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id VARCHAR(180) NOT NULL UNIQUE,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
  supplier_invoice_number VARCHAR(120),
  bill_date DATE NOT NULL,
  total_amount NUMERIC(14, 2) NOT NULL CHECK (total_amount >= 0),
  status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS supplier_bill_grn_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_bill_id BIGINT NOT NULL REFERENCES supplier_bills(id) ON DELETE CASCADE,
  goods_receipt_id BIGINT NOT NULL REFERENCES goods_receipts(id),
  allocated_amount NUMERIC(14, 2) NOT NULL CHECK (allocated_amount >= 0),
  UNIQUE (supplier_bill_id, goods_receipt_id)
);

CREATE TABLE IF NOT EXISTS payment_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  payment_entity_type VARCHAR(40) NOT NULL,
  payment_entity_id VARCHAR(180) NOT NULL,
  payment_origin_branch_id INTEGER NOT NULL REFERENCES branches(id),
  payment_origin_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  target_entity_type VARCHAR(40) NOT NULL,
  target_entity_id VARCHAR(180) NOT NULL,
  target_branch_id INTEGER NOT NULL REFERENCES branches(id),
  target_operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  allocated_amount NUMERIC(14, 2) NOT NULL CHECK (allocated_amount > 0),
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (company_id, payment_origin_branch_id, payment_origin_location_id)
    REFERENCES operational_locations(company_id, branch_id, id),
  FOREIGN KEY (company_id, target_branch_id, target_operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS dispatch_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id VARCHAR(180) NOT NULL UNIQUE,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  source_branch_id INTEGER NOT NULL REFERENCES branches(id),
  source_operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  batch_number VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  created_by INTEGER NOT NULL REFERENCES users(id),
  source_device_id VARCHAR(160) REFERENCES authorized_devices(device_id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (company_id, batch_number),
  FOREIGN KEY (company_id, source_branch_id, source_operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS inventory_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  global_id VARCHAR(180) NOT NULL UNIQUE,
  dispatch_batch_id BIGINT REFERENCES dispatch_batches(id),
  company_id INTEGER NOT NULL REFERENCES companies(id),
  source_branch_id INTEGER NOT NULL REFERENCES branches(id),
  source_operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  destination_branch_id INTEGER NOT NULL REFERENCES branches(id),
  destination_operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  initiation_mode VARCHAR(40) NOT NULL,
  transfer_number VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
  state_version INTEGER NOT NULL DEFAULT 1,
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  requested_by INTEGER NOT NULL REFERENCES users(id),
  approved_by INTEGER REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (company_id, transfer_number),
  CHECK (source_operational_location_id <> destination_operational_location_id),
  FOREIGN KEY (company_id, source_branch_id, source_operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id),
  FOREIGN KEY (company_id, destination_branch_id, destination_operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

CREATE TABLE IF NOT EXISTS inventory_transfer_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL REFERENCES inventory_transfers(id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id),
  source_lot_id INTEGER NOT NULL REFERENCES inventory_batches(id),
  requested_quantity NUMERIC(14, 3) NOT NULL CHECK (requested_quantity > 0),
  approved_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (approved_quantity >= 0),
  reserved_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (reserved_quantity >= 0),
  dispatched_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (dispatched_quantity >= 0),
  received_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (received_quantity >= 0),
  rejected_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (rejected_quantity >= 0),
  damaged_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (damaged_quantity >= 0),
  short_quantity NUMERIC(14, 3) NOT NULL DEFAULT 0 CHECK (short_quantity >= 0),
  original_cost_rate NUMERIC(14, 4),
  CHECK (approved_quantity <= requested_quantity),
  CHECK (reserved_quantity <= approved_quantity),
  CHECK (dispatched_quantity <= approved_quantity),
  CHECK (received_quantity + rejected_quantity + damaged_quantity + short_quantity <= dispatched_quantity)
);

CREATE TABLE IF NOT EXISTS inventory_transfer_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL REFERENCES inventory_transfers(id) ON DELETE CASCADE,
  event_type VARCHAR(60) NOT NULL,
  from_status VARCHAR(40),
  to_status VARCHAR(40) NOT NULL,
  quantity_details JSONB NOT NULL DEFAULT '{}'::jsonb,
  notes TEXT,
  user_id INTEGER NOT NULL REFERENCES users(id),
  device_id VARCHAR(160) NOT NULL REFERENCES authorized_devices(device_id),
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  server_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  branch_id INTEGER NOT NULL REFERENCES branches(id),
  operational_location_id INTEGER NOT NULL REFERENCES operational_locations(id),
  inventory_batch_id INTEGER NOT NULL REFERENCES inventory_batches(id),
  transfer_item_id BIGINT REFERENCES inventory_transfer_items(id),
  quantity NUMERIC(14, 3) NOT NULL CHECK (quantity > 0),
  status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  idempotency_key VARCHAR(220) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  released_at TIMESTAMP,
  FOREIGN KEY (company_id, branch_id, operational_location_id)
    REFERENCES operational_locations(company_id, branch_id, id)
);

-- Add nullable shadow scope to current operational tables. Enforcement is enabled
-- only after an owner-approved backfill and client rollout.
ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE inventory_batches ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE stock_adjustments ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE stock_adjustments ADD COLUMN IF NOT EXISTS branch_id INTEGER REFERENCES branches(id);
ALTER TABLE stock_adjustments ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE purchases ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE sales ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE sale_payments ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sale_returns ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE sale_returns ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE waste_entries ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE waste_entries ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE customer_payments ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE customer_payments ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE customer_ledger ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE customer_ledger ADD COLUMN IF NOT EXISTS branch_id INTEGER REFERENCES branches(id);
ALTER TABLE customer_ledger ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE supplier_payments ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE contra_entries ADD COLUMN IF NOT EXISTS company_id INTEGER REFERENCES companies(id);
ALTER TABLE contra_entries ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);

ALTER TABLE sync_processed_operations ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sync_processed_operations ADD COLUMN IF NOT EXISTS assignment_generation INTEGER;
ALTER TABLE sync_change_log ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sync_change_log ADD COLUMN IF NOT EXISTS assignment_generation INTEGER;
ALTER TABLE sync_conflict_log ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sync_conflict_log ADD COLUMN IF NOT EXISTS assignment_generation INTEGER;
ALTER TABLE sync_pos_sale_staging ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sync_pos_sale_staging ADD COLUMN IF NOT EXISTS assignment_generation INTEGER;
ALTER TABLE sync_inbox_operations ADD COLUMN IF NOT EXISTS operational_location_id INTEGER REFERENCES operational_locations(id);
ALTER TABLE sync_inbox_operations ADD COLUMN IF NOT EXISTS assignment_generation INTEGER;

CREATE INDEX IF NOT EXISTS inventory_batches_location_fifo_idx
  ON inventory_batches(company_id, branch_id, operational_location_id, product_id, purchase_date, created_at, id)
  WHERE remaining_qty > 0;
CREATE INDEX IF NOT EXISTS sync_change_log_location_cursor_idx
  ON sync_change_log(company_id, branch_id, operational_location_id, change_id);
CREATE INDEX IF NOT EXISTS sync_processed_location_idx
  ON sync_processed_operations(company_id, branch_id, operational_location_id, device_id, processed_at);
