-- Owner-managed branch, operational-location, staff, and device scope metadata.
-- Additive only. This migration creates no branches, locations, assignments, or approvals.

ALTER TABLE authorized_devices ADD COLUMN IF NOT EXISTS requested_physical_location VARCHAR(180);
ALTER TABLE authorized_devices ADD COLUMN IF NOT EXISTS requested_intended_usage VARCHAR(80);
ALTER TABLE authorized_devices ADD COLUMN IF NOT EXISTS requested_user_id INTEGER REFERENCES users(id);
ALTER TABLE authorized_devices ADD COLUMN IF NOT EXISTS requested_role_id INTEGER REFERENCES roles(id);

CREATE TABLE IF NOT EXISTS operational_scope_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  entity_type VARCHAR(60) NOT NULL,
  entity_id VARCHAR(180) NOT NULL,
  action VARCHAR(60) NOT NULL,
  old_value JSONB,
  new_value JSONB,
  reason TEXT NOT NULL,
  changed_by INTEGER NOT NULL REFERENCES users(id),
  changed_by_device_id VARCHAR(160) NOT NULL REFERENCES authorized_devices(device_id),
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS operational_scope_audit_entity_idx
  ON operational_scope_audit(company_id, entity_type, entity_id, changed_at DESC);
