"use strict";

/**
 * What the hosted database already had on 2026-09-21, and therefore need not be migrated.
 *
 * ## Why a list of names is checked into the repository
 *
 * `initializeDatabase()` is the only place the `CREATE TABLE IF NOT EXISTS` and
 * `ALTER TABLE ... ADD COLUMN IF NOT EXISTS` statements live, and it is hard-off on a hosted
 * deployment. So anything added to it reaches the cloud only if somebody also writes a migration.
 * Forgetting that has now cost three outages:
 *
 *     users.failed_login_attempts       -> every cloud sign-in answered 500, for two weeks
 *     charge_types                      -> the reference bootstrap answered 500, so no rebuilt
 *                                          device could be filled
 *     device_control_settings.auto_update_*  -> the backend refused to boot at all, for two days
 *
 * Each was found from a Railway log. This file is how the next one is found from `npm test`.
 *
 * ## Why these entries are exempt, and why that is sound rather than convenient
 *
 * On 2026-09-21 the hosted backend started clean, which it does only when `verifyDeclaredSchema`
 * finds no drift at all. That is a measurement, not an assumption: the live cloud database
 * contained every table and column declared here on that date. They cannot need a migration,
 * because they are already there.
 *
 * ## How to use it
 *
 * **Do not add to this list.** It records a date that has passed. Anything declared after it is
 * new, and new means a migration under `backend/migrations/cloud/` registered in
 * `scripts/run-cloud-migrations.js`. `cloudSchemaCoverage.test.js` enforces exactly that, and the
 * entry then needs no line here -- the migration is what covers it.
 *
 * The one honest exception is `excused`, for something deliberately kept off the cloud. It takes a
 * reason a person can check, the way `deliberatelyNotRun` does in the migration runner. It is empty
 * today, and an empty escape hatch that exists is better than a test somebody deletes.
 */

const recordedAt = "2026-09-21";

/** Tables already present on the hosted database on 2026-09-21. */
const tables = [
  "account_recovery_requests",
  "accounts",
  "activation_codes",
  "ai_action_proposals",
  "ai_alerts",
  "ai_audit_log",
  "ai_cache",
  "ai_conversations",
  "ai_engine_events",
  "ai_fact_snapshots",
  "ai_messages",
  "ai_reminders",
  "ai_settings",
  "ai_token_usage",
  "auth_audit_log",
  "authorized_devices",
  "backup_logs",
  "backup_settings",
  "branches",
  "business_settings",
  "contra_entries",
  "counters",
  "customer_ledger",
  "customer_payment_audit",
  "customer_payments",
  "customers",
  "device_audit_trail",
  "device_control_settings",
  "device_exit_attempt_logs",
  "expense_audit_trail",
  "expenses",
  "frost_memories",
  "frost_prediction_accuracy",
  "frost_prediction_runs",
  "frost_predictions",
  "inventory_batches",
  "lot_discount_audit",
  "lot_discounts",
  "mandi_tax_rules",
  "owner_admin_support_contacts",
  "payment_settings",
  "pos_rate_override_audit",
  "pos_settings",
  "product_audit_trail",
  "product_categories",
  "product_category_audit_trail",
  "product_duplicate_archive_log",
  "products",
  "purchase_audit_trail",
  "purchase_items",
  "purchases",
  "rebate_rules",
  "role_permission_settings",
  "roles",
  "sale_audit_trail",
  "sale_batch_allocations",
  "sale_discount_rules",
  "sale_items",
  "sale_payments",
  "sale_permission_settings",
  "sale_rate_history",
  "sale_rate_settings",
  "sale_return_items",
  "sale_returns",
  "sales",
  "stock_adjustments",
  "stock_transactions",
  "supplier_payment_audit",
  "supplier_payments",
  "suppliers",
  "sync_change_log",
  "sync_conflict_log",
  "sync_pos_sale_staging",
  "sync_processed_operations",
  "sync_queue",
  "sync_settings",
  "sync_test_entities",
  "update_center",
  "users",
  "waste_entries",
  "whatsapp_send_logs",
  "whatsapp_settings",
];

/** Columns already present, as `table.column`. */
const columns = [
  "accounts.whatsapp_number",
  "accounts.whatsapp_opt_in",
  "ai_settings.ai_provider_enabled",
  "ai_settings.branch_id",
  "ai_settings.company_id",
  "ai_settings.frost_settings",
  "ai_settings.thresholds",
  "authorized_devices.app_version",
  "authorized_devices.assigned_branch_id",
  "authorized_devices.assigned_counter_id",
  "authorized_devices.last_active_at",
  "authorized_devices.last_sync_at",
  "authorized_devices.local_ip",
  "authorized_devices.platform",
  "authorized_devices.sync_status",
  "branches.active",
  "branches.address",
  "branches.created_at",
  "branches.gst_number",
  "branches.location",
  "branches.phone_number",
  "branches.updated_at",
  "business_settings.auto_print_after_billing",
  "business_settings.default_invoice_print",
  "business_settings.default_printer_type",
  "business_settings.default_report_print",
  "business_settings.hide_zero_discount_rows",
  "business_settings.receipt_width",
  "business_settings.show_bill_discount_row_receipt",
  "business_settings.show_item_discount_column_pos",
  "business_settings.show_item_discount_column_receipt",
  "business_settings.show_print_preview_before_print",
  "contra_entries.cancelled",
  "contra_entries.cancelled_at",
  "contra_entries.cancelled_by",
  "customer_ledger.customer_id",
  "customer_ledger.transaction_date",
  "customer_payments.counter_id",
  "customer_payments.edit_reason",
  "customer_payments.edited_at",
  "customer_payments.edited_by",
  "customers.account_number",
  "customers.alternate_number",
  "customers.bank_name",
  "customers.city",
  "customers.firm_name",
  "customers.ifsc_code",
  "customers.system_account",
  "customers.upi_id",
  "customers.whatsapp_number",
  "customers.whatsapp_opt_in",
  "expenses.cancellation_reason",
  "expenses.cancelled_at",
  "expenses.cancelled_by",
  "expenses.counter_id",
  "expenses.edit_reason",
  "expenses.edited_at",
  "expenses.edited_by",
  "expenses.paid_to",
  "expenses.status",
  "inventory_batches.adjusted_qty",
  "inventory_batches.balance_amount",
  "inventory_batches.deleted_at",
  "inventory_batches.entity_version",
  "inventory_batches.freight_charges",
  "inventory_batches.gross_amount",
  "inventory_batches.labour_charges",
  "inventory_batches.lot_name",
  "inventory_batches.lot_size",
  "inventory_batches.mandi_tax_amount",
  "inventory_batches.net_payable",
  "inventory_batches.origin_type",
  "inventory_batches.other_charges",
  "inventory_batches.payment_timing",
  "inventory_batches.purchase_bill_status",
  "inventory_batches.purchase_id",
  "inventory_batches.rebate_amount",
  "inventory_batches.remarks",
  "inventory_batches.returned_qty",
  "inventory_batches.temporary_sale_rate",
  "inventory_batches.transfer_in_qty",
  "inventory_batches.transfer_out_qty",
  "inventory_batches.unit",
  "inventory_batches.updated_at",
  "inventory_batches.waste_qty",
  "payment_settings.enable_sales_mandi_tax",
  "payment_settings.qr_display_size",
  "payment_settings.sales_mandi_tax_basis",
  "payment_settings.sales_mandi_tax_customer_scope",
  "payment_settings.sales_mandi_tax_disable_reason",
  "payment_settings.sales_mandi_tax_effective_date",
  "payment_settings.sales_mandi_tax_percent",
  "payment_settings.sales_mandi_tax_product_scope",
  "payment_settings.show_upi_qr_on_all_bills",
  "product_categories.deleted_at",
  "product_categories.entity_version",
  "product_categories.global_id",
  "products.active",
  "products.archive_reason",
  "products.archived_at",
  "products.archived_duplicate_of",
  "products.barcode",
  "products.category",
  "products.category_id",
  "products.deleted_at",
  "products.entity_version",
  "products.global_id",
  "products.minimum_stock",
  "products.origin_type",
  "products.remarks",
  "products.selling_rate_updated_at",
  "products.selling_rate_updated_by",
  "purchase_items.basic_amount",
  "purchase_items.effective_cost_per_unit",
  "purchase_items.freight_charges",
  "purchase_items.labour_charges",
  "purchase_items.lot_name",
  "purchase_items.lot_size",
  "purchase_items.mandi_tax_amount",
  "purchase_items.net_payable",
  "purchase_items.origin_type",
  "purchase_items.other_charges",
  "purchase_items.rebate_amount",
  "purchase_items.unit",
  "purchases.balance_amount",
  "purchases.basic_amount",
  "purchases.bill_date",
  "purchases.bill_number",
  "purchases.cancellation_reason",
  "purchases.cancelled_at",
  "purchases.cancelled_by",
  "purchases.counter_id",
  "purchases.edit_reason",
  "purchases.edited_at",
  "purchases.edited_by",
  "purchases.effective_cost_per_unit",
  "purchases.expected_purchase_rate",
  "purchases.freight_charges",
  "purchases.gross_amount",
  "purchases.labour_charges",
  "purchases.lot_name",
  "purchases.lot_size",
  "purchases.mandi_tax_amount",
  "purchases.mandi_tax_percent",
  "purchases.net_payable",
  "purchases.other_charges",
  "purchases.paid_amount",
  "purchases.payment_date",
  "purchases.payment_due_days",
  "purchases.payment_mode",
  "purchases.payment_reference_number",
  "purchases.payment_status",
  "purchases.payment_timing",
  "purchases.purchase_bill_status",
  "purchases.purchase_status",
  "purchases.purchase_type",
  "purchases.rebate_amount",
  "purchases.rebate_percent",
  "purchases.rebate_rule_id",
  "purchases.remarks",
  "purchases.stock_source",
  "purchases.supplier_id",
  "purchases.temporary_sale_rate",
  "sale_items.cost_status",
  "sale_items.default_selling_rate",
  "sale_items.discount_amount",
  "sale_items.lot_discount_id",
  "sale_items.lot_discount_type",
  "sale_items.lot_discount_value",
  "sale_items.manual_rate_override",
  "sale_items.net_amount",
  "sale_payments.branch_id",
  "sale_payments.device_id",
  "sale_payments.payment_time",
  "sale_payments.reference_number",
  "sale_payments.status",
  "sale_payments.user_id",
  "sale_rate_settings.bill_level_slab_discount_enabled",
  "sale_rate_settings.pos_lot_selection_mode",
  "sale_returns.counter_id",
  "sales.backdate_reason",
  "sales.backdated_bill",
  "sales.bill_datetime",
  "sales.cancellation_reason",
  "sales.cancelled_at",
  "sales.cancelled_by",
  "sales.counter_id",
  "sales.credit_remarks",
  "sales.credit_status",
  "sales.customer_id",
  "sales.customer_mobile",
  "sales.customer_name",
  "sales.customer_notes",
  "sales.discount_rule_id",
  "sales.discount_rule_name",
  "sales.discount_rule_payment_mode",
  "sales.discount_rule_type",
  "sales.discount_rule_value",
  "sales.due_date",
  "sales.edit_reason",
  "sales.edited_at",
  "sales.edited_by",
  "sales.entity_version",
  "sales.global_id",
  "sales.gross_amount",
  "sales.invoice_discount_amount",
  "sales.invoice_no",
  "sales.item_discount_amount",
  "sales.mandi_tax_basis",
  "sales.mandi_tax_effective_date",
  "sales.mandi_tax_rate",
  "sales.offline_invoice_ref",
  "sales.payment_mode",
  "sales.profit_status",
  "sales.sale_status",
  "sales.source_device_id",
  "sales.tax_amount",
  "sales.tax_config_snapshot",
  "sales.taxable_amount",
  "sales.transaction_date",
  "supplier_payments.cancellation_reason",
  "supplier_payments.cancelled",
  "supplier_payments.cancelled_at",
  "supplier_payments.cancelled_by",
  "supplier_payments.counter_id",
  "supplier_payments.edit_reason",
  "supplier_payments.edited_at",
  "supplier_payments.edited_by",
  "suppliers.whatsapp_number",
  "suppliers.whatsapp_opt_in",
  "sync_settings.device_display_name",
  "users.counter_id",
  "users.email",
  "users.force_password_change",
  "users.joining_date",
  "users.last_login_at",
  "users.locked_until",
  "users.mobile_number",
  "users.notes",
  "users.password_changed_at",
  "users.pending_recovery_email",
  "users.pending_recovery_mobile",
  "users.recovery_email",
  "users.recovery_email_verified",
  "users.recovery_email_verified_at",
  "users.recovery_enabled",
  "users.recovery_mobile",
  "users.recovery_mobile_verified",
  "users.recovery_mobile_verified_at",
  "users.session_revocation_version",
  "users.staff_self_recovery_enabled",
  "users.updated_at",
  "users.verified_email",
  "users.verified_mobile",
  "waste_entries.counter_id",
];

/**
 * Declared but deliberately never migrated, each with a reason somebody can check.
 *
 * Keyed by table name or `table.column`. Empty is the correct state; a growing one means the
 * cloud and the code are drifting on purpose, which is worth having to write down.
 */
const excused = {};

module.exports = { recordedAt, tables, columns, excused };
